#:schema node_modules/wrangler/config-schema.json
name = "database"
main = "src/index.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

services = [{ binding = "STORAGE", service = "storage" }]

[[d1_databases]]
binding = "DB"
database_name = "d1-virtualbox"
database_id = "61d24aaf-46ea-4411-b452-310b6852e533"