#:schema node_modules/wrangler/config-schema.json
name = "storage"
main = "src/index.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2"
bucket_name = "cccestorage"